@hostname = https://localhost:7217
###
POST {{hostname}}/api/auth/register
Content-Type: application/json
{
  "Username": "happinaith",
  "Email": "testuser@example.com",
  "Password": "TestPassword123!"
}
###
@name loginRequest
POST {{hostname}}/api/auth/login
Content-Type: application/json
{
  "Email": "testuser@example.com",
  "Password": "TestPassword123!"
}
###
POST {{hostname}}/api/auth/login
Content-Type: application/json
{
  "Email": "testuser@example.com",
  "Password": "TestPassword12!"
}
###
@authToken = {{loginRequest.response.body.$.Token}}

### Создать новый проект (Токен подставляется автоматически!)
POST {{hostname}}/api/projects
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Империя CAESAR (MVP)"
}

### 5. Получить список моих проектов
GET {{hostname}}/api/projects
Accept: application/json
Authorization: Bearer {{authToken}}

### Созданние новой страницы в проекте
POST {{hostname}}/api/projectpages
Content-Type: application/json
{
  "projectId": 4,
  "name": "Команда FrontEnd"
}

### Перемещение задачи по статусам и позиции
PUT {{hostname}}/api/tasks/1/move
Content-Type: application/json
{
  "targetTaskStatus": 2,
  "NewPosition": 1
}
### Создание новой задачи
POST {{hostname}}/api/tasks
Content-Type: application/json
{
  "projectPageId": 2,
  "title": "Тестовая задача",
  "description": "Описание тестовой задачи",
  "deadline": "2024-06-30T12:00:00Z"
}