@hostname=https://localhost:7217

POST {{hostname}}/api/projects
Content-Type: application/json
{
  "name": "Тест"
}

### Получение списка всех проектов у пользователя
GET {{hostname}}/api/projects
Accept: application/json