# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostname=https://localhost:7217
### 
PUT {{hostname}}/api/tasks/1/move
Content-Type: application/json
{
  "targetTaskStatus": 1,
  "NewPosition": 1
}
### Создание новой задачи
POST {{hostname}}/api/tasks
Content-Type: application/json
{
  "projectPageId": 2,
  "title": "Тестовая задача",
  "description": "Описание тестовой задачи",
  "deadline": "2024-06-30T12:00:00Z"
}